### ISSUE TITLE
Code crashes, probably outdated

### ISSUE THREAD

**Issue by Darth-Carrotpie** [protyposis/LibSampleRate.NET#1]
Backend: .NET Standard 2.1
Steps: Run Demo code
Outcome: Crash, no errors/exceptions. Compiler does not throw up and compiles.
Environment/Compiler: Unity 2021.2.7f1 (il2cpp compiler)

This probably needs adapting to newer versions of .NET.
Although it's strange.. because it compiles without errors, just crashes when run. Perhaps a mistake in all that **unsafe** code?

**Comment by protyposis** [comment]
If it crashes there must be an error message. What is it?

I just tested it in VS2019 and it works out of the box. If you look at the demo code you'll see that all it does is resample a few samples, print one line to the console (only the console, not the debug output window of your IDE), and exit.
https://github.com/protyposis/SRC.NET/blob/42bbb673e0452816edd25b173ba6e5944006aa13/SRC.NET/LibSampleRate.Demo/Program.cs#L82-L85

**Comment by Darth-Carrotpie** [comment]
The thing is, that there is no message. It's just a hard crash without any messages or prompts.
My use case attempt was to convert a single input (I get a small data amount per each frame) to a required sample rate (44.1kHz to 16kHz), in order to be able to input that resampled data into a neural network.
So it's basically a real-time use case attempt:

```
public class SRCConverter {
    SampleRateConverter src;
    int inputSampleCount;
    int outputSampleCount;
    float[] outputBuffer = new float[2048];
    int inputRate, outputRate;

    public SRCConverter(int _inputRate, int _outputRate) {
        src = new SampleRateConverter(ConverterType.SRC_SINC_MEDIUM_QUALITY, 1);
        inputRate = _inputRate;
        outputRate = _outputRate;
    }

    public float[] SingleConversion(float[] sourceData) {
        src.SetRatio(outputRate / inputRate);
        src.Process(sourceData, 0, sourceData.Length,
            outputBuffer, 0, outputBuffer.Length,
            true, out inputSampleCount, out outputSampleCount);

        float[] output = new float[outputSampleCount];
        Array.Copy(outputBuffer, output, outputSampleCount);
        output = outputBuffer;
        return output;
    }
}
```
Usage:
```float[] data = converter.SingleConversion(_input.audioDataSlice.ToArray());```
**audioDataSlice[]** is quite small, around 60-70 values. Could that be the problem? Does it expect large arrays?

**Comment by protyposis** [comment]
A small number of samples should be fine. If the number is too small you just won't get any output until you feed it more data. Then my guess would be an incompatibility with your Unity environment - can't help with that, sorry.

**Comment by Darth-Carrotpie** [comment]
I see. Oh well :(
BTW, when you tested it, was it on Dot NET Standard 2.1?

**Comment by protyposis** [comment]
https://github.com/protyposis/SRC.NET/blob/42bbb673e0452816edd25b173ba6e5944006aa13/SRC.NET/LibSampleRate/LibSampleRate.csproj#L12
